# Generated by Django 5.1.1 on 2025-01-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorGradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_data', to='excel_app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorMatrixData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(null=True)),
                ('ongoing_project', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_data', to='excel_app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSpendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_data', to='excel_app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSpendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vendor_spend_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='excel_app.vendorspenddata')),
            ],
        ),
        migrations.CreateModel(
            name='VendorYearGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grade', models.CharField(max_length=50, null=True)),
                ('vendor_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_grades', to='excel_app.vendorgradedata')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProgramValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.programattribute')),
                ('vendor_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_values', to='excel_app.vendormatrixdata')),
            ],
            options={
                'unique_together': {('vendor_matrix', 'program')},
            },
        ),
    ]
