# Generated by Django 5.1.1 on 2025-01-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorGradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, null=True)),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('vendor_code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorMatrixData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('gipv', models.TextField(null=True)),
                ('cost_reduction_activity', models.TextField(null=True)),
                ('ppkv', models.TextField(null=True)),
                ('dte', models.TextField(null=True)),
                ('beep', models.TextField(null=True)),
                ('tmiep', models.TextField(null=True)),
                ('trade_mission', models.TextField(null=True)),
                ('lean_mgmt', models.TextField(null=True)),
                ('kaizen', models.TextField(null=True)),
                ('icc', models.TextField(null=True)),
                ('contract_nego_skill', models.TextField(null=True)),
                ('sspoa', models.TextField(null=True)),
                ('espo', models.TextField(null=True)),
                ('vip2', models.TextField(null=True)),
                ('ir4', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('ongoing_project', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSpendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('vendor_code', models.CharField(max_length=50, null=True)),
                ('overall_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSpendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vendor_spend_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='excel_app.vendorspenddata')),
            ],
        ),
        migrations.CreateModel(
            name='VendorYearGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grade', models.CharField(max_length=50, null=True)),
                ('vendor_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_grades', to='excel_app.vendorgradedata')),
            ],
        ),
    ]
