# Generated by Django 5.1.1 on 2025-01-22 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='beep',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='contract_nego_skill',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='cost_reduction_activity',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='dte',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='espo',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='gipv',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='icc',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='ir4',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='kaizen',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='lean_mgmt',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='ppkv',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='sspoa',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='tmiep',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='trade_mission',
        ),
        migrations.RemoveField(
            model_name='vendormatrixdata',
            name='vip2',
        ),
        migrations.CreateModel(
            name='VendorProgramValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.programattribute')),
                ('vendor_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_values', to='excel_app.vendormatrixdata')),
            ],
            options={
                'unique_together': {('vendor_matrix', 'program')},
            },
        ),
    ]
