# Generated by Django 5.1.1 on 2024-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='name',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='overall_2018',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='overall_2019',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='overall_2020',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='overall_2021',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='overall_2022',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='vendor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='vendor_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
