# Generated by Django 5.1.1 on 2024-10-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0002_remove_exceldata_address_remove_exceldata_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
