# Generated by Django 5.1.1 on 2024-10-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0003_exceldata_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='grand_total_2018',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='grand_total_2019',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='grand_total_2020',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='grand_total_2021',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='grand_total_2022',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='grand_total_2023',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='overall_5_years',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
