# Generated by Django 5.1.1 on 2024-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0004_exceldata_grand_total_2018_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorGradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, null=True)),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('vendor_code', models.CharField(max_length=50, null=True)),
                ('overall_2018', models.CharField(max_length=50, null=True)),
                ('overall_2019', models.CharField(max_length=50, null=True)),
                ('overall_2020', models.CharField(max_length=50, null=True)),
                ('overall_2021', models.CharField(max_length=50, null=True)),
                ('overall_2022', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelData',
        ),
    ]
