# Generated by Django 5.1.1 on 2024-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0005_vendorgradedata_delete_exceldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSpendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
