# Generated by Django 5.1.1 on 2024-10-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0006_vendorspenddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorSpendData',
        ),
    ]
