# Generated by Django 5.1.1 on 2024-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0008_vendorspenddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorspenddata',
            name='vendor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorspenddata',
            name='vendor_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
