# Generated by Django 5.1.1 on 2024-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0009_vendorspenddata_vendor_vendorspenddata_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMatrixData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('gipv', models.CharField(max_length=5, null=True)),
                ('cost_reduction_activity', models.CharField(max_length=5, null=True)),
                ('ppkv', models.CharField(max_length=5, null=True)),
                ('dte', models.CharField(max_length=5, null=True)),
                ('beep', models.CharField(max_length=5, null=True)),
                ('tmiep', models.CharField(max_length=5, null=True)),
                ('trade_mision', models.CharField(max_length=5, null=True)),
                ('lean_mgmt', models.CharField(max_length=5, null=True)),
                ('kaizen', models.CharField(max_length=5, null=True)),
                ('icc', models.CharField(max_length=5, null=True)),
                ('contract_nego_skill', models.CharField(max_length=5, null=True)),
                ('sspoa', models.CharField(max_length=5, null=True)),
                ('espo', models.CharField(max_length=5, null=True)),
                ('vip2', models.CharField(max_length=5, null=True)),
                ('ir4', models.CharField(max_length=5, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('ongoing_project', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
