# Generated by Django 5.1.1 on 2024-10-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0010_vendormatrixdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='ongoing_project',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
