# Generated by Django 5.1.1 on 2024-11-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0011_alter_vendormatrixdata_ongoing_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendormatrixdata',
            old_name='trade_mision',
            new_name='trade_mission',
        ),
    ]
