# Generated by Django 5.1.1 on 2025-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0012_rename_trade_mision_vendormatrixdata_trade_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='beep',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='contract_nego_skill',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='cost_reduction_activity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='dte',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='espo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='gipv',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='icc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='ir4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='kaizen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='lean_mgmt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='ppkv',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='sspoa',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='tmiep',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='trade_mission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendormatrixdata',
            name='vip2',
            field=models.TextField(null=True),
        ),
    ]
